<?php

namespace Crawl\CommonBundle\Repository;

/**
 * DoubleColorBallsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoubleColorBallsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findArray($issue)
    {
        return $this->createQueryBuilder('q')
            ->select('q')
            ->where('q.issue = :issue')
            ->setParameter('issue', $issue)
            ->getQuery()
            ->getArrayResult();
    }
}
