<?php

namespace Crawl\CommonBundle\Repository;

/**
 * DoubleColorBallsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoubleColorBallsRepository extends \Doctrine\ORM\EntityRepository
{
}
