<?php

namespace Crawl\CommonBundle\Repository;

/**
 * RestaurantFoodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantFoodsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array
     */
    public function findArray($id)
    {
        return $this->createQueryBuilder('q')
            ->select('q')
            ->leftJoin('q.Restaurant', 'r')
            ->where('r.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getArrayResult();
    }
}
