<?php

namespace Crawl\CommonBundle\Repository;

/**
 * RestaurantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class RestaurantsRepository
 * @package Crawl\CommonBundle\Repository
 */
class RestaurantsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array
     */
    public function findArray()
    {
        return $this->createQueryBuilder('q')
            ->select('q')
            ->getQuery()
            ->getArrayResult();
    }
}
