<?php

namespace Crawl\CommonBundle\Repository;

/**
 * RestaurantFoodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantFoodsRepository extends \Doctrine\ORM\EntityRepository
{
}
