<?php

namespace Crawl\CommonBundle\Repository;

/**
 * WordCollinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordCollinsRepository extends \Doctrine\ORM\EntityRepository
{
}
