<?php

namespace Crawl\CommonBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * WordCollinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordCollinsRepository extends EntityRepository
{
}
