imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: security.yml }

framework:
#    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: true
#    form:            ~
    csrf_protection: ~
    templating:
        engines: ['twig']
#    validation:      { enable_annotations: true }
#    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

monolog:
    handlers:
        applog:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.crawl.log"
            level: error