crawl_api:
    resource: "@CrawlApiBundle/Resources/config/routing.yml"
    prefix: /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect