crawl_word_api:
    resource: "@CrawlApiBundle/Resources/config/routing/word_api.yml"
    prefix:   /api/word

crawl_takeout_api:
    resource: "@CrawlApiBundle/Resources/config/routing/takeout_api.yml"
    prefix:   /api/takeout

crawl_double_color_ball_api:
    resource: "@CrawlApiBundle/Resources/config/routing/double_color_ball_api.yml"
    prefix:   /api/dcd

crawl_instagram_api:
    resource: "@CrawlApiBundle/Resources/config/routing/instagram_api.yml"
    prefix:   /api/instagram

crawl_weibo_api:
    resource: "@CrawlApiBundle/Resources/config/routing/weibo_api.yml"
    prefix:   /api/weibo