services:
    # helper
    crawl_common.helper.curl:
        class: Crawl\CommonBundle\Helper\CurlHelper

    crawl_common.helper.word:
        class: Crawl\CommonBundle\Helper\WorkHelper

    crawl_common.helper.takeout:
        class: Crawl\CommonBundle\Helper\TakeoutHelper

    # service
    crawl_common.service.word:
        class: Crawl\CommonBundle\Service\WorkService
        calls:
            - [ setContainer, [ '@service_container' ] ]

    # EventListener
    crawl_common.event_listener.persist:
        class: Crawl\CommonBundle\EventListener\PersistEventListener
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }